# Generated by Django 5.0.7 on 2024-08-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_service', '0002_rename_cafe_entrepreneurship_features_ecosystemcriteria_ce_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldetail',
            name='delivery_range',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
