# Generated by Django 5.0.7 on 2024-08-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0008_userprofile_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cafe_entrepreneurship_user',
            field=models.BooleanField(default=False),
        ),
    ]
