# Generated by Django 5.0.7 on 2024-08-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0009_user_is_cafe_entrepreneurship_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('lite', 'Lite'), ('pro', 'Pro'), ('none', 'None')], default='none', max_length=4, null=True),
        ),
    ]
