# Generated by Django 5.0.7 on 2024-08-12 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe_entrepreneurship', '0001_initial'),
        ('common_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistDietaryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('con_num_verify', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'is_food_service_user': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_accountholder_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=555, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('weburl', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=500, null=True)),
                ('headquarter', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('account_holder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_service.accountholder')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_service_branch', to='common_data.state')),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'is_food_service_user': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_branch_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='food-service/additional-detail/logo')),
                ('menu', models.ImageField(blank=True, null=True, upload_to='food-service/additional-detail/menu')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='food-service/additional-detail/cover')),
                ('min_bio', models.CharField(blank=True, max_length=555, null=True)),
                ('cafe_registration', models.CharField(blank=True, max_length=250, null=True)),
                ('sunday_availability', models.BooleanField(default=False)),
                ('sunday_opening_time', models.TimeField(blank=True, null=True)),
                ('sunday_closing_time', models.TimeField(blank=True, null=True)),
                ('monday_availability', models.BooleanField(default=False)),
                ('monday_opening_time', models.TimeField(blank=True, null=True)),
                ('monday_closing_time', models.TimeField(blank=True, null=True)),
                ('tuesday_availability', models.BooleanField(default=False)),
                ('tuesday_opening_time', models.TimeField(blank=True, null=True)),
                ('tuesday_closing_time', models.TimeField(blank=True, null=True)),
                ('wednesday_availability', models.BooleanField(default=False)),
                ('wednesday_opening_time', models.TimeField(blank=True, null=True)),
                ('wednesday_closing_time', models.TimeField(blank=True, null=True)),
                ('thursday_availability', models.BooleanField(default=False)),
                ('thursday_opening_time', models.TimeField(blank=True, null=True)),
                ('thursday_closing_time', models.TimeField(blank=True, null=True)),
                ('friday_availability', models.BooleanField(default=False)),
                ('friday_opening_time', models.TimeField(blank=True, null=True)),
                ('friday_closing_time', models.TimeField(blank=True, null=True)),
                ('saturday_availability', models.BooleanField(default=False)),
                ('saturday_opening_time', models.TimeField(blank=True, null=True)),
                ('saturday_closing_time', models.TimeField(blank=True, null=True)),
                ('delivery_available', models.BooleanField(default=False)),
                ('delivery_range', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'is_food_service_user': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_additional_detail_user', to=settings.AUTH_USER_MODEL)),
                ('branch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_service.branch')),
                ('product_types', models.ManyToManyField(blank=True, to='food_service.producttype')),
                ('service_categories', models.ManyToManyField(blank=True, to='food_service.servicecategory')),
                ('specialist_dietary_services', models.ManyToManyField(blank=True, to='food_service.specialistdietaryservice')),
            ],
        ),
        migrations.CreateModel(
            name='EcosystemCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_entrepreneurship_operational_status', models.CharField(blank=True, choices=[('planning', 'Planning to open'), ('open', 'Open for business'), ('exiting', 'Looking to exit')], max_length=10, null=True)),
                ('branch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_service.branch')),
                ('cafe_entrepreneurship_features', models.ManyToManyField(blank=True, to='cafe_entrepreneurship.feature')),
                ('cafe_entrepreneurship_specialist_dietary_services', models.ManyToManyField(blank=True, to='cafe_entrepreneurship.specialistdietaryservice')),
                ('cafe_entrepreneurship_state', models.ManyToManyField(related_name='fs_ecosystem_criteria_state_for_ce', to='common_data.state')),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'is_food_service_user': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_ecosystem_criteria_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('additional_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='food_service.additionaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food-service/additionaldetail/images')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('additional_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='food_service.additionaldetail')),
            ],
        ),
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='media-gallery/files/')),
                ('approved', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_service.branch')),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'is_food_service_user': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_media_gallery_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, max_length=100, null=True)),
                ('review_link', models.CharField(blank=True, max_length=555, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('additional_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='food_service.additionaldetail')),
            ],
        ),
    ]
