# Generated by Django 5.0.7 on 2024-08-12 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cafe-entrepreneurship/additional-detail/images')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, max_length=100, null=True)),
                ('review_link', models.CharField(blank=True, max_length=555, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistDietaryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('con_num_verify', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'is_cafe_entrepreneurship_user': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ce_accountholder_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_status', models.CharField(choices=[('planning', 'Planning to open'), ('open', 'Open for business'), ('exiting', 'Looking to exit')], default='planning', max_length=10)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abn', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=555, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('weburl', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=500, null=True)),
                ('flagship', models.BooleanField(default=False)),
                ('subscription_type', models.CharField(blank=True, choices=[('lite', 'Lite'), ('pro', 'Pro')], max_length=4, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('account_holder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe_entrepreneurship.accountholder')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ce_branch_state', to='common_data.state')),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'is_cafe_entrepreneurship_user': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ce_branch_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cafe-entrepreneurship/additional-detail/logo')),
                ('menu', models.ImageField(blank=True, null=True, upload_to='cafe-entrepreneurship/additional-detail/menu')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cafe-entrepreneurship/additional-detail/cover')),
                ('min_bio', models.CharField(blank=True, max_length=555, null=True)),
                ('cafe_registration', models.CharField(blank=True, max_length=250, null=True)),
                ('sunday_availability', models.BooleanField(default=False)),
                ('sunday_opening_time', models.TimeField(blank=True, null=True)),
                ('sunday_closing_time', models.TimeField(blank=True, null=True)),
                ('monday_availability', models.BooleanField(default=False)),
                ('monday_opening_time', models.TimeField(blank=True, null=True)),
                ('monday_closing_time', models.TimeField(blank=True, null=True)),
                ('tuesday_availability', models.BooleanField(default=False)),
                ('tuesday_opening_time', models.TimeField(blank=True, null=True)),
                ('tuesday_closing_time', models.TimeField(blank=True, null=True)),
                ('wednesday_availability', models.BooleanField(default=False)),
                ('wednesday_opening_time', models.TimeField(blank=True, null=True)),
                ('wednesday_closing_time', models.TimeField(blank=True, null=True)),
                ('thursday_availability', models.BooleanField(default=False)),
                ('thursday_opening_time', models.TimeField(blank=True, null=True)),
                ('thursday_closing_time', models.TimeField(blank=True, null=True)),
                ('friday_availability', models.BooleanField(default=False)),
                ('friday_opening_time', models.TimeField(blank=True, null=True)),
                ('friday_closing_time', models.TimeField(blank=True, null=True)),
                ('saturday_availability', models.BooleanField(default=False)),
                ('saturday_opening_time', models.TimeField(blank=True, null=True)),
                ('saturday_closing_time', models.TimeField(blank=True, null=True)),
                ('delivery_available', models.BooleanField(default=False)),
                ('delivery_range', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'is_cafe_entrepreneurship_user': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ce_additional_detail_user', to=settings.AUTH_USER_MODEL)),
                ('ambiences', models.ManyToManyField(blank=True, to='cafe_entrepreneurship.ambience')),
                ('branch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe_entrepreneurship.branch')),
            ],
        ),
        migrations.CreateModel(
            name='EcosystemCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('branch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe_entrepreneurship.branch')),
            ],
        ),
    ]
