# Generated by Django 5.0.7 on 2024-08-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe_entrepreneurship', '0001_initial'),
        ('common_data', '0001_initial'),
        ('food_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecosystemcriteria',
            name='food_service_product_types',
            field=models.ManyToManyField(blank=True, to='food_service.producttype'),
        ),
        migrations.AddField(
            model_name='ecosystemcriteria',
            name='food_service_service_categories',
            field=models.ManyToManyField(blank=True, to='food_service.servicecategory'),
        ),
        migrations.AddField(
            model_name='ecosystemcriteria',
            name='food_service_specialist_dietary_services',
            field=models.ManyToManyField(blank=True, to='food_service.specialistdietaryservice'),
        ),
        migrations.AddField(
            model_name='ecosystemcriteria',
            name='food_service_state',
            field=models.ManyToManyField(blank=True, related_name='ce_ecosystem_criteria_state_for_fd', to='common_data.state'),
        ),
    ]
