# Generated by Django 5.0.7 on 2024-08-12 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe_entrepreneurship', '0002_initial'),
        ('common_data', '0001_initial'),
        ('trade_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ecosystemcriteria',
            name='trade_service_service_categories',
            field=models.ManyToManyField(blank=True, to='trade_service.servicecategory'),
        ),
        migrations.AddField(
            model_name='ecosystemcriteria',
            name='trade_service_state',
            field=models.ManyToManyField(blank=True, related_name='ce_ecosystem_criteria_state_for_td', to='common_data.state'),
        ),
        migrations.AddField(
            model_name='ecosystemcriteria',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_food_service_user': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ce_ecosystem_criteria_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='additional_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cafe_entrepreneurship.additionaldetail'),
        ),
        migrations.AddField(
            model_name='additionaldetail',
            name='features',
            field=models.ManyToManyField(blank=True, to='cafe_entrepreneurship.feature'),
        ),
        migrations.AddField(
            model_name='image',
            name='additional_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cafe_entrepreneurship.additionaldetail'),
        ),
        migrations.AddField(
            model_name='additionaldetail',
            name='menu_highlights',
            field=models.ManyToManyField(blank=True, to='cafe_entrepreneurship.menuhighlight'),
        ),
        migrations.AddField(
            model_name='review',
            name='additional_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cafe_entrepreneurship.additionaldetail'),
        ),
        migrations.AddField(
            model_name='additionaldetail',
            name='specialist_dietary_services',
            field=models.ManyToManyField(blank=True, to='cafe_entrepreneurship.specialistdietaryservice'),
        ),
        migrations.AddField(
            model_name='additionaldetail',
            name='techstacks',
            field=models.ManyToManyField(blank=True, to='cafe_entrepreneurship.techstack'),
        ),
    ]
