# Generated by Django 5.0.7 on 2024-08-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_entrepreneurship', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecosystemcriteria',
            old_name='food_service_product_types',
            new_name='fs_product_types',
        ),
        migrations.RenameField(
            model_name='ecosystemcriteria',
            old_name='food_service_service_categories',
            new_name='fs_service_categories',
        ),
        migrations.RenameField(
            model_name='ecosystemcriteria',
            old_name='food_service_specialist_dietary_services',
            new_name='fs_specialist_dietary_services',
        ),
        migrations.RenameField(
            model_name='ecosystemcriteria',
            old_name='food_service_state',
            new_name='fs_state',
        ),
        migrations.RenameField(
            model_name='ecosystemcriteria',
            old_name='trade_service_service_categories',
            new_name='ts_service_categories',
        ),
        migrations.RenameField(
            model_name='ecosystemcriteria',
            old_name='trade_service_state',
            new_name='ts_state',
        ),
    ]
