# Generated by Django 5.0.7 on 2024-08-12 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_entrepreneurship', '0004_rename_food_service_product_types_ecosystemcriteria_fs_product_types_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecosystemcriteria',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_cafe_entrepreneurship_user': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ce_ecosystem_criteria_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
