# Generated by Django 5.0.7 on 2024-08-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_entrepreneurship', '0005_alter_ecosystemcriteria_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldetail',
            name='delivery_range',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
