# Generated by Django 5.0.7 on 2024-08-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_entrepreneurship', '0008_declined'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Declined',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
