# Generated by Django 5.0.7 on 2024-08-14 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_entrepreneurship', '0009_alter_like_unique_together_remove_like_branch_and_more'),
        ('food_service', '0003_alter_additionaldetail_delivery_range'),
        ('trade_service', '0003_alter_additionaldetail_delivery_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Declined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fs_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ce_declined_for_fs', to='food_service.branch')),
                ('ts_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ce_declined_for_ts', to='trade_service.branch')),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'is_cafe_entrepreneurship_user': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ce_declined_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fs_branch'), ('user', 'ts_branch')},
            },
        ),
    ]
